init test

diff --git a/.github/workflows/bump-version.yml b/.github/workflows/bump-version.yml
--- a/.github/workflows/bump-version.yml
+++ b/.github/workflows/bump-version.yml
@@ -11,15 +11,21 @@ permissions:
 
 jobs:
   bump-version:
-    if: "!contains(github.event.head_commit.message, '[skip ci]')"
     runs-on: ubuntu-latest
-
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
         with:
-          fetch-depth: 0  # Important if you want to access full git history
+          fetch-depth: 0
 
+      - name: Check for [skip ci] commit message
+        id: check_skip
+        run: |
+          echo "Commit message: ${{ github.event.head_commit.message }}"
+          if echo "${{ github.event.head_commit.message }}" | grep -iq '\[skip ci\]'; then
+            echo "Skipping workflow because commit message contains [skip ci]"
+            exit 78  # special exit code to tell GitHub to neutralize the workflow (neutral)
+          fi
       - name: Set up Node.js
         uses: actions/setup-node@v4
         with:
